### ISSUE TITLE
CI Failures

### ISSUE THREAD

**Issue by mrocklin** [dask/dask-examples#162]
It looks like CI is now failing

https://travis-ci.org/github/dask/dask-examples/builds/716774531

Some highlights

<details>

<summary> Prophet install </summary

```python-traceback
   command: /home/travis/miniconda/envs/test/bin/python3.8 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-n5i_pkvw/fbprophet/python/setup.py'"'"'; __file__='"'"'/tmp/pip-install-n5i_pkvw/fbprophet/python/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-emefs74w
       cwd: /tmp/pip-install-n5i_pkvw/fbprophet/python
  Complete output (44 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib
  creating build/lib/fbprophet
  creating build/lib/fbprophet/stan_model
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-n5i_pkvw/fbprophet/python/setup.py", line 122, in <module>
      setup(
    File "/home/travis/miniconda/envs/test/lib/python3.8/site-packages/setuptools/__init__.py", line 163, in setup
      return distutils.core.setup(**attrs)
    File "/home/travis/miniconda/envs/test/lib/python3.8/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/home/travis/miniconda/envs/test/lib/python3.8/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/home/travis/miniconda/envs/test/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/home/travis/miniconda/envs/test/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 223, in run
      self.run_command('build')
    File "/home/travis/miniconda/envs/test/lib/python3.8/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/home/travis/miniconda/envs/test/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/home/travis/miniconda/envs/test/lib/python3.8/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/home/travis/miniconda/envs/test/lib/python3.8/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/home/travis/miniconda/envs/test/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/pip-install-n5i_pkvw/fbprophet/python/setup.py", line 48, in run
      build_models(target_dir)
    File "/tmp/pip-install-n5i_pkvw/fbprophet/python/setup.py", line 36, in build_models
      from fbprophet.models import StanBackendEnum
    File "/tmp/pip-install-n5i_pkvw/fbprophet/python/fbprophet/__init__.py", line 8, in <module>
      from fbprophet.forecaster import Prophet
    File "/tmp/pip-install-n5i_pkvw/fbprophet/python/fbprophet/forecaster.py", line 17, in <module>
      from fbprophet.make_holidays import get_holiday_names, make_holidays_df
    File "/tmp/pip-install-n5i_pkvw/fbprophet/python/fbprophet/make_holidays.py", line 14, in <module>
      import fbprophet.hdays as hdays_part2
    File "/tmp/pip-install-n5i_pkvw/fbprophet/python/fbprophet/hdays.py", line 13, in <module>
      from convertdate.islamic import from_gregorian, to_gregorian
  ModuleNotFoundError: No module named 'convertdate'
  ----------------------------------------
  ERROR: Failed building wheel for fbprophet
  Running setup.py clean for fbprophet
  ERROR: Command errored out with exit status 1:
   command: /home/travis/miniconda/envs/test/bin/python3.8 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-n5i_pkvw/fbprophet/python/setup.py'"'"'; __file__='"'"'/tmp/pip-install-n5i_pkvw/fbprophet/python/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' clean --all
       cwd: /tmp/pip-install-n5i_pkvw/fbprophet
  Complete output (5 lines):
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-n5i_pkvw/fbprophet/python/setup.py", line 119, in <module>
      with open('requirements.txt', 'r') as f:
  FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
  ----------------------------------------
  ERROR: Failed cleaning build dir for fbprophet
  Building wheel for pystan (setup.py): started
  Building wheel for pystan (setup.py): finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: /home/travis/miniconda/envs/test/bin/python3.8 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-n5i_pkvw/pystan/setup.py'"'"'; __file__='"'"'/tmp/pip-install-n5i_pkvw/pystan/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-149xclu8
       cwd: /tmp/pip-install-n5i_pkvw/pystan/
  Complete output (1 lines):
  Cython>=0.22 and NumPy are required.
```

</details>

<details>

<summary> Version check issue </summary>

```
Function:  execute_task
args:      ((<function fit at 0x7f2cd61d4280>, DecisionTreeClassifier(max_depth=4, min_samples_leaf=4, min_samples_split=9), (<function cv_extract at 0x7f2cd61d5e50>, <dask_ml.model_selection.methods.CVCache object at 0x7f2cd61cfa60>, array([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  1., 10., ...,  2.,  0.,  0.],
       ...,
       [ 0.,  6., 16., ..., 11.,  1.,  0.],
       [ 0.,  0., 10., ...,  8.,  6.,  0.],
       [ 0.,  0.,  7., ...,  0.,  0.,  0.]]), array([4, 4, 5, 2, 1, 5, 6, 7, 7, 7, 3, 6, 3, 2, 9, 5, 2, 8, 2, 7, 5, 7,
       5, 5, 4, 8, 5, 6, 4, 2, 0, 7, 3, 5, 5, 4, 7, 4, 8, 9, 3, 1, 0, 5,
       1, 9, 6, 9, 1, 0, 5, 5, 8, 3, 8, 8, 9, 1, 2, 5, 8, 9, 6, 1, 7, 9,
       7, 8, 9, 8, 0, 4, 5, 3, 0, 1, 3, 7, 7, 1, 1, 8, 3, 2, 8, 9, 3, 2,
       7]), True, True, 0), (<function cv_extract at 0x7f2cd61d5e50>, <dask_ml.model_selection.methods.CVCache object at 0x7f2cd61cfa60>, array([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., .
kwargs:    {}
Exception: TypeError("'<' not supported between instances of 'Version' and 'tuple'")
```

</details>

<details>

<summary> TPot </summary>

```python-traceback
nbconvert.preprocessors.execute.CellExecutionError: An error occurred while executing the following cell:
------------------
tp.fit(X_train, y_train)
------------------
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
~/miniconda/envs/test/lib/python3.8/site-packages/tpot/base.py in fit(self, features, target, sample_weight, groups)
    713                 warnings.simplefilter('ignore')
--> 714                 self._pop, _ = eaMuPlusLambda(
    715                     population=self._pop,
~/miniconda/envs/test/lib/python3.8/site-packages/tpot/gp_deap.py in eaMuPlusLambda(population, toolbox, mu, lambda_, cxpb, mutpb, ngen, pbar, stats, halloffame, verbose, per_generation_function)
    225 
--> 226     population[:] = toolbox.evaluate(population)
    227 
~/miniconda/envs/test/lib/python3.8/site-packages/tpot/base.py in _evaluate_individuals(self, population, features, target, sample_weight, groups)
   1333                             warnings.simplefilter('ignore')
-> 1334                             tmp_result_scores = list(dask.compute(*tmp_result_scores))
   1335 
~/miniconda/envs/test/lib/python3.8/site-packages/dask/base.py in compute(*args, **kwargs)
    443 
--> 444     results = schedule(dsk, keys, **kwargs)
    445     return repack([f(r, *a) for r, (f, a) in zip(results, postcomputes)])
~/miniconda/envs/test/lib/python3.8/site-packages/distributed/client.py in get(self, dsk, keys, restrictions, loose_restrictions, resources, sync, asynchronous, direct, retries, priority, fifo_timeout, actors, **kwargs)
   2687             try:
-> 2688                 results = self.gather(packed, asynchronous=asynchronous, direct=direct)
   2689             finally:
~/miniconda/envs/test/lib/python3.8/site-packages/distributed/client.py in gather(self, futures, errors, direct, asynchronous)
   1981                 local_worker = None
-> 1982             return self.sync(
   1983                 self._gather,
~/miniconda/envs/test/lib/python3.8/site-packages/distributed/client.py in sync(self, func, asynchronous, callback_timeout, *args, **kwargs)
    831         else:
--> 832             return sync(
    833                 self.loop, func, *args, callback_timeout=callback_timeout, **kwargs
~/miniconda/envs/test/lib/python3.8/site-packages/distributed/utils.py in sync(loop, func, callback_timeout, *args, **kwargs)
    338         typ, exc, tb = error[0]
--> 339         raise exc.with_traceback(tb)
    340     else:
~/miniconda/envs/test/lib/python3.8/site-packages/distributed/utils.py in f()
    322                 future = asyncio.wait_for(future, callback_timeout)
--> 323             result[0] = yield future
    324         except Exception as exc:
~/miniconda/envs/test/lib/python3.8/site-packages/tornado/gen.py in run(self)
    734                     try:
--> 735                         value = future.result()
    736                     except Exception:
~/miniconda/envs/test/lib/python3.8/site-packages/distributed/client.py in _gather(self, futures, errors, direct, local_worker)
   1846                         else:
-> 1847                             raise exception.with_traceback(traceback)
   1848                         raise exc
~/miniconda/envs/test/lib/python3.8/site-packages/dask_ml/model_selection/methods.py in cv_extract()
    165 def cv_extract(cvs, X, y, is_X, is_train, n):
--> 166     return cvs.extract(X, y, n, is_X, is_train)
    167 
~/miniconda/envs/test/lib/python3.8/site-packages/dask_ml/model_selection/methods.py in extract()
    110                 return self._extract_pairwise(X, y, n, is_train=is_train)
--> 111             return self._extract(X, y, n, is_x=True, is_train=is_train)
    112         if y is None:
~/miniconda/envs/test/lib/python3.8/site-packages/dask_ml/model_selection/methods.py in _extract()
    130         inds = self.splits[n][0] if is_train else self.splits[n][1]
--> 131         result = _safe_indexing(X if is_x else y, inds)
    132 
~/miniconda/envs/test/lib/python3.8/site-packages/dask_ml/model_selection/utils.py in _safe_indexing()
    219     elif hasattr(X, "shape"):
--> 220         return _array_indexing(X, indices, indices_dtype, axis=axis)
    221     else:
~/miniconda/envs/test/lib/python3.8/site-packages/dask_ml/model_selection/utils.py in _array_indexing()
    298     """Index an array or scipy.sparse consistently across NumPy version."""
--> 299     if np_version < (1, 12) or sp.issparse(array):
    300         # FIXME: Remove the check for NumPy when using >= 1.12
TypeError: '<' not supported between instances of 'Version' and 'tuple'
During handling of the above exception, another exception occurred:
RuntimeError                              Traceback (most recent call last)
<ipython-input-7-c5bcc440217f> in <module>
----> 1 tp.fit(X_train, y_train)
~/miniconda/envs/test/lib/python3.8/site-packages/tpot/base.py in fit(self, features, target, sample_weight, groups)
    754                     # raise the exception if it's our last attempt
    755                     if attempt == (attempts - 1):
--> 756                         raise e
    757             return self
    758 
~/miniconda/envs/test/lib/python3.8/site-packages/tpot/base.py in fit(self, features, target, sample_weight, groups)
    745                         self._pbar.close()
    746 
--> 747                     self._update_top_pipeline()
    748                     self._summary_of_best_pipeline(features, target)
    749                     # Delete the temporary cache before exiting
~/miniconda/envs/test/lib/python3.8/site-packages/tpot/base.py in _update_top_pipeline(self)
    827             # If user passes CTRL+C in initial generation, self._pareto_front (halloffame) shoule be not updated yet.
    828             # need raise RuntimeError because no pipeline has been optimized
--> 829             raise RuntimeError('A pipeline has not yet been optimized. Please call fit() first.')
    830 
    831     def _summary_of_best_pipeline(self, features, target):
RuntimeError: A pipeline has not yet been optimized. Please call fit() first.
RuntimeError: A pipeline has not yet been optimized. Please call fit() first.
```

</details>

**Comment by TomAugspurger** [comment]
I'll take a look today or Monday.
