### ISSUE TITLE
Workspace not showing up

### ISSUE THREAD

**Issue by mrocklin** [dask/dask-examples#80]
When we first load the page, the dashboard address isn't populated and the task stream and progress plots aren't arranged on the screen.  

My first guess was that this was due to a change in the workspace file spec, so I decided to generate a new one.  However I ran into an error that I don't fully underestand.

```
jovyan@jupyter-dask-2ddask-2dexamples-2d4c9mozvq:~$ jupyter lab workspaces export 
```
```python-traceback
Traceback (most recent call last):
  File "/srv/conda/envs/notebook/bin/jupyter-lab", line 10, in <module>
    sys.exit(main())
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/jupyter_core/application.py", line 266, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/notebook/notebookapp.py", line 1758, in start
    super(NotebookApp, self).start()
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/jupyter_core/application.py", line 255, in start
    self.subapp.start()
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/jupyterlab/labapp.py", line 276, in start
    super().start()
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/jupyter_core/application.py", line 255, in start
    self.subapp.start()
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/jupyterlab/labapp.py", line 136, in start
    page_url = config.page_url
AttributeError: 'LabConfig' object has no attribute 'page_url'
```
cc @ian-r-rose

**Comment by ian-r-rose** [comment]
The churn in the last week has been challenging to keep up with -- that has been fixed in master but not in the released alpha yet. I'll get a fix for that here as soon as I can. I'm not sure why my `cp` workaround didn't have the desired affect: if I run the `start` script manually in the binder container it seems to work.

**Comment by mrocklin** [comment]
No worries.  Thanks for the explanation.  It's ok if things aren't optimal
on our end for a little while.  I'm looking forward to the 1.0.0 release :)

**Comment by mrocklin** [comment]
Thanks @ian-r-rose !
